### ISSUE TITLE
期待支持SFC

### ISSUE THREAD

**Issue by Yunnathai** [dwqs/vue-to-react#1]
## Your Code
```
// your code is here
```

期待支持SFC

**Comment by dwqs** [comment]
@jamninetyfive I will try it and welcome PRs

**Comment by dwqs** [comment]
有了可行的思路：

![image](https://user-images.githubusercontent.com/7871813/40422321-9684a5bc-5ec1-11e8-841b-7ccd7828f6e2.png)

**Comment by Yunnathai** [comment]
哇 。真的强。- 期待正式用上。

**Comment by dwqs** [comment]
@jamninetyfive 0.0.8已经支持转换 sfc 的基础功能
